config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  get 'search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

    validates :title, presence: true
    validates :body, presence: true, length: {maximum: 200}

def self.search(search, word)
  if search == "forward_match"
    @book = Book.where("title LIKE?","#{word}%")
  elsif search == "backward_match"
    @book = Book.where("title LIKE?","%#{word}")
  elsif search == "perfect_match"
    @book = Book.where("title LIKE?","#{word}")
  elsif search == "partial_match"
    @book = Book.where("title LIKE?","%#{word}%")
  else
    @book = Book.all
  end
end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followeds, through: :active_relationships, source: :follower
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :followed

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(followed_id: user.id).present?
  end

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  attachment :profile_image


def self.search(search,word)
  if search == "forward_match"
    @user = User.where("name LIKE?","#{word}%")
  elsif search == "backward_match"
    @user = User.where("name LIKE?","%#{word}")
  elsif search == "perfect_match"
    @user = User.where("name LIKE?","#{word}")
  elsif search == "partial_match"
    @user = User.where("name LIKE?","%#{word}%")
  else
    @user = User.all
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      redirect_back(fallback_location: root_path)
    else
      @new_book = Book.new
      @user = @book.user
      flash[:notice] =  "エラー#{@book_comment.errors.full_messages}"
      redirect_to book_path(@book)
    end
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    # @users = User.find(params[:id])
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
    flash[:notice] = "You have created book successfully."
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
    flash[:notice] = "You have updated book successfully."
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

   def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
   end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    search = params[:search]
    @word = params[:word]

    if @range == '1'
      @user = User.search(search,@word)
    else
      @book = Book.search(search,@word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @user.user_id = current_user.id
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    # @post_images = @user.post_images.page(params[:page]).reverse_order
    @books = @user.books
    @book = Book.new
  end

  def follows
    user = User.find(params[:id])
    @users = user.followeds
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
    flash[:notice] = "You have updated user successfully."
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("book_comment<%= book.id %>").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("book_comment<%= book.id %>").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation">
  <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  <ul>
    <li>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    </li>
  <% end %>
  </ul>
  </div>
  <% end %>
<%= form_with model:@book,  local:true do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title, class:'form-control book_title' %>
</div>
<div class="form-group">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class:'form-control book_body' %>
</div>
<div class="form-group">
  <%= f.submit 'Update Book', class:'btn btn-success' %>
</div>
<% end %>
<%= link_to "Show", book_path(@book) %>
|
<%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <div id="error_explanation">
  <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  <ul>
    <li>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    </li>
  <% end %>
  </ul>
  </div>
  <% end %>

<div class="row">
<%= render 'users/user', user: @user, book: @book %>


<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
<thead>
<tr>
<th></th>
<th>Title</th>
<th>Opinion</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>
  <td>
    <%= link_to user_path(book.user) do %>
    <%= attachment_image_tag book.user,:profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
    <% end %>
  </td>
  <td><%= link_to book.title, book_path(book.id) %></td>
  <td><%= book.body %></td>
  <!--<td><= link_to "Edit", edit_book_path(book.id) %></td>-->
  <!--<td><= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure"%></td>-->
  <td id="favorite-btn<%= book.id %>">
    <%= render 'favorites/favorite-btn', book: book %>
  </td>
  <td id="book_comment<%= book.id %>">コメント数: <%= book.book_comments.count %></td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
<p id = "notice"><%= flash[:notice] %></p>
<% end %>
<div class="container">

  <div class="row">
    <%= render 'users/user', user: @user, book: @new_book %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%= link_to @book.user.name,  user_path(@book.user.id) %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class:'btn btn-sm btn-success edit_book_1304' %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class:'btn btn-sm btn-danger destroy_book_1304' %></td>
            <% else %>
            <td id="favorite-btn<%= @book.id %>">
              <%= render 'favorites/favorite-btn', book: @book %>
            </td>
            <% end %>
            <td>コメント数: <%= @book.book_comments.count %></td>
          </tr>
        </tbody>
      </table>
      <table class="comment">
        <tbody>
        <!--<p>コメント件数：<= @post_image.post_comments.count %></p>-->
          <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
              </td>
              <td><%= book_comment.comment %></td>
              <% if book_comment.user == current_user %>
                <td class="comment-delete">
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:'btn btn-sm btn-danger destroy_book_1304' %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <!--< if @book_comment.errors.any? %>-->
      <!--  <div id="error_explanation">-->
      <!--    <h3><= @book_comment.errors.count %> error prohibited this obj from being saved:</h3>-->
      <!--    <ul>-->
      <!--      <li>-->
      <!--        < @book_comment.errors.full_messages.each do |message| %>-->
      <!--          <= message %>-->
      <!--        < end %>-->
      <!--      </li>-->
      <!--    </ul>-->
      <!--  </div>-->
      <!--< end %>-->
      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
        <div class="new-comment">
          <%= f.text_area :comment, rows:'5', class:"form-control" %>
        </div>
        <%= f.submit "送信" %>
      <% end %>
    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      ♥<%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      ♡<%= book.favorites.count %>
    <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
<p id = "notice"><%= flash[:notice] %></p>
<% end %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
      </h1>
      <p>
        In <i class="fas fa-book"></i><strong>Bookers</strong>,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row"><%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %></div>
        <div class="row"><%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %></div>
      </div>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<!--books一覧 -->
<table class="table table-hover table-inverse">
　<% if @range == '2' %>
　<h3>Books search for "<%= @word %>"</h3>
  <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
     <% @book.each do |book| %>
     <tr>
      <td>
       <%= link_to(book.user) do %>
       <%= attachment_image_tag book.user,:profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
       <% end %>
      </td>
      <td>
       <%= link_to book.title, book_path(book.id) %>
      </td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
  </tbody>

  <% else %>
  <h3>Users search for "<%= @word %>"</h3>
  <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
     <tr>
      <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
      <td><%= user.name%></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
     </tr>
    <% end %>
   </tbody>
   <% end %>
 </table>

app/views/users/_user.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
  <div class="col-md-3">
    <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
  <table class="table">
  <tbody>
  <tr>
   <th>name</th>
   <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to follows_user_path(user.id) do %>
        <%= user.followeds.count %>
      <% end %>
    </th>
  </tr><tr>
    <th>followers</th>
    <th>
      <%= link_to followers_user_path(user.id) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
  </tbody>
  </table>
  <!--<h3>Introduction</h3><h3 class="profile-Introduction"><= @user.introduction, fallback: null %></h3>-->
  <% if current_user != user %>
    <div class="from-group">
      <% if user.followed_by?(current_user) %>
        <%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class:'btn btn-success' %>
      <% else %>
        <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class:'btn btn-success' %>
      <% end %>
    </div>
  <% else %>
    <div class="row">
      <%= link_to "", edit_user_path(user), class:'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_173' %>
    </div>
  <% end %>

<h2 class="mt-3">New book</h2>
<!-- form_with部分 -->
<%= form_with model: book, local:true do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title , class:"form-control book_title" %>
</div>

<div class="form-group">
  <labek for="book_opinion">Opinion</label>
  <%= f.text_area :body, class:"form-control book_body" %>
</div>

<div class="form-group">
  <%= f.submit 'Create Book', class:'btn btn-success' %>
</div>

<% end %>
  </div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
  <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
  <ul>
    <li>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
    </li>
  <% end %>
  </ul>
  </div>
  <% end %>
  <div class="form-group">
   <label for="inputName">Name</label>
   <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class:"form-control name"%>
  </div>
  <div class="form-group">
   <label for="inputImage">Image</label>
   <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:"form-control-file user_image" %>
  </div>
  <div class="form-group">
   <label for="user_introduction">Introduction</label>
   <%= f.text_area :introduction , class:"form-control introduction"%>
  </div>

  <%= f.submit "Update User" , class:"btn btn-secondary"%>
<% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div>
<h2>Follower Users</h2>
<% if @users.any? %>
<table class="table">
<thead>
<tr>
<th>image</th>
<th>name</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
  <td>
    <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
  </td>
  <td><%= user.name %></td>
  <td>フォロー数: <%= user.followeds.count %></td>
  <td>フォロワー数: <%= user.followers.count %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
  <!--<td><= link_to "Edit", edit_book_path(book.id) %></td>-->
  <!--<td><= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure"%></td>-->
</tr>
<% end %>
</tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>
</div>

app/views/users/follows.html.erb
<div>
<h2>Follow Users</h2>
<% if @users.any? %>
<table class="table">
<thead>
<tr>
<th>image</th>
<th>name</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
  <td>
    <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
  </td>
  <td><%= user.name %></td>
  <td>フォロー数: <%= user.followeds.count %></td>
  <td>フォロワー数: <%= user.followers.count %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
  <!--<td><= link_to "Edit", edit_book_path(book.id) %></td>-->
  <!--<td><= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure"%></td>-->
</tr>
<% end %>
</tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">
<%= render 'users/user', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class="table">
<thead>
<tr>
<th>image</th>
<th>name</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
  <td>
    <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
  </td>
  <td><%= user.name %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
  <!--<td><= link_to "Edit", edit_book_path(book.id) %></td>-->
  <!--<td><= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure"%></td>-->
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
<p id = "notice"><%= flash[:notice] %></p>
<% end %>
<%= render 'users/user', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
<thead>
<tr>
<th></th>
<th>Title</th>
<th>Opinion</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>
  <td>
    <%= link_to user_path(book.user) do %>
    <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
    <% end %>
  </td>
  <td><%= link_to book.title, book_path(book.id) %></td>
  <td><%= book.body %></td>
  <!--<td><= link_to "Edit", edit_book_path(book.id) %></td>-->
  <!--<td><= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure"%></td>-->
  <td>コメント数: <%= book.book_comments.count %></td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>